#%RAML 1.0 DataType
properties:
  AccountDimensionID:
    description: AccountDimensionID 
    type: string
    required: true

  ProductDimensionCatagoryID:
    description: ProductDimensionCatagoryID 
    type: string
    required: true
  AccountDimensionExternalID:
    description: AccountDimensionExternalID 
    type: string
    required: true
  PromotionDimensionID:
    description: PromotionDimensionID 
    type: string
    required: true
  ProductDimensionExternalID:
    description: ProductDimensionExternalID 
    type: string
    required: true
  Label:
    description: Label 
    type: string
    required: true
  MeasureCode:
    description: MeasureCode 
    type: string
    required: true
  Month1:
    description: Month1 
    type: string
    required: true
  Month2:
    description: Month2
    type: string
    required: true
  Month3:
    description: Month3 
    type: string
    required: true
  Month4:
    description: Month4 
    type: string
    required: true
  Month5:
    description: Month5 
    type: string
    required: true
  Month6:
    description: Month6 
    type: string
    required: true
  Month7:
    description: Month7 
    type: string
    required: true
  Month8:
    description: Month8
    type: string
    required: true
  Month9:
    description: Month9 
    type: string
    required: true
  Month10:
    description: Month10 
    type: string
    required: true
  Month11:
    description: Month11 
    type: string
    required: true
  Month12:
    description: Month12 
    type: string
    required: true
