#%RAML 1.0 SecurityScheme
type: x-client-credentials
describedBy:
  headers:
    clientId:
      type: string
      example: "1231123123"
      required: true
    clientSecret:
      type: string
      example: "1231231231"
      required: true
  responses:
    401:
      body:
        application/json:
          example: !include ../examples/error401.raml